package ua.training.electriberies.model.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import ua.training.electriberies.model.dao.interfaces.GenericDAO;
import ua.training.electriberies.model.dao.interfaces.QueryConstants;
import ua.training.electriberies.model.entity.users.*;

public class JDBCUserDAO implements GenericDAO<User> {
	
	private static final String GET_BY_ID = QueryConstants.GET_USER_BY_ID_QUERY;
	private static final String GET_BY_LOGIN = QueryConstants.GET_USER_BY_LOGIN_QUERY;
	private static final String GET_ALL = QueryConstants.GET_ALL_USERS_QUERY;
	private static final String INSERT_USER = QueryConstants.INSERT_USER_QUERY;
	private static final String DELETE_USER = QueryConstants.DELETE_USER_QUERY;
	private static final String UPDATE_USER = QueryConstants.UPDATE_USER_QUERY;

	private static final String ID = QueryConstants.USER_ID_COLUMN;
	private static final String LOGIN = QueryConstants.USER_LOGIN_COLUMN;
	private static final String PASSWORD = QueryConstants.USER_PASSWORD_COLUMN;
	private static final String ROLE = QueryConstants.USER_ROLE_COLUMN;
	
	
	private Connection connection;

	public JDBCUserDAO(Connection connection) {
		this.connection = connection;
	}
	
	/**
	 * @return User
	 * Return statement added to provide testability of this method. 
	 * Method returns the same user was inserted to DB but with userId generated by DB auto increment,
	 * just inserted to DB user is found by login which is unique.
	 *  
	 */
	@Override
	public User create (User user) {
		try(PreparedStatement statement = connection.prepareStatement(INSERT_USER)) {
			statement.setString(1, user.getLogin());
			statement.setString(2, user.getPassword());
			statement.setString(3, user.getRole().name());			
			if (statement.executeUpdate() > 0) {
				User newUser = getByLogin(user.getLogin());
				return newUser;
			}
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
		return null;
	}

	@Override
	public User getById(int id) {
		User user = null;		
		try(PreparedStatement statement = connection.prepareStatement(GET_BY_ID)) {
			statement.setInt(1, id);
			ResultSet rs = statement.executeQuery();
			if (rs.next()) {
				user = extractUser(rs);	
			}
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}		
		return user;
	}
	
	private User getByLogin(String login) {
		User user = null;		
		try(PreparedStatement statement = connection.prepareStatement(GET_BY_LOGIN)) {
			statement.setString(1, login);
			ResultSet rs = statement.executeQuery();
			if (rs.next()) {
				user = extractUser(rs);	
			}
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}		
		return user;
	}

	private User extractUser(ResultSet rs) throws SQLException {
		int userid = rs.getInt(ID);
		String login = rs.getString(LOGIN);
		String password = rs.getString(PASSWORD);
		String role = rs.getString(ROLE);
		
		return new UserImpl(userid, login, password, UserRole.valueOf(role));
	}

	@Override
	public User update(User user) {
		try(PreparedStatement statement = connection.prepareStatement(UPDATE_USER)) {
			statement.setString(1, user.getLogin());
			statement.setString(2, user.getPassword());
			statement.setString(3, user.getRole().name());
			statement.setInt(4, user.getId());
			if (statement.executeUpdate() > 0) {
				return user;
			}
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
		return null;
		
	}

	@Override
	public User delete(User user) {
		try(PreparedStatement statement = connection.prepareStatement(DELETE_USER)) {
			statement.setInt(1, user.getId());
			int res = statement.executeUpdate();
			if (res > 0) {
				return user;
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			throw new RuntimeException(e);
		}
		return null;
	}

	@Override
	public List<User> getAll() {
		List<User> users = new ArrayList<>();		
		try(PreparedStatement statement = connection.prepareStatement(GET_ALL)) {
			ResultSet rs = statement.executeQuery();
			while(rs.next()) {
				User user = extractUser(rs);			
				users.add(user);	
			}
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}				
		return users;
	}

	@Override
	public void close() {
		try {
			connection.close();
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}		
	}	

}
